services:
  db:
    image: mysql:8.4.6
    command: ["mysqld"]
    restart: always
    healthcheck:
      # cmd will return status 0 even without creds, stating 
      # that the server is up
      test: ["CMD", "mysqladmin" ,"ping"]
      timeout: 20s
      interval: 3s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "database_name"
      MYSQL_USER: "db_username"
      MYSQL_PASSWORD: "db_password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_db:/var/lib/mysql
    networks:
      - mysql_network
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file: ".env"
    networks:
      - mysql_network
    depends_on:
      db:
        condition: service_healthy
networks:
  mysql_network:
    driver: bridge
volumes:
  mysql_db: